name: Deploy to Aptible

on:
  workflow_run:
    workflows: ["Run tests"]
    types: [completed]
    branches: [main, add-aptible-env-vars-to-deployment-#184227131]
  workflow_dispatch:
    inputs: { }

env:
  USERNAME: ${{ secrets.GPR_USER }}
  TOKEN: ${{ secrets.GPR_KEY }}

jobs:
  deploy:
    name: Deploy to Aptible
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}
          fetch-depth: 0
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2.3.1
        with:
          key: ${{ secrets.APTIBLE_SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.APTIBLE_KNOWN_HOSTS }}
      - name: Push to Aptible remote branch and deploy
        run: |
          ssh-keyscan beta.aptible.com >> ~/.ssh/known_hosts
          git remote add aptible git@beta.aptible.com:form-flow-staging/demo.git
          git push --force git@beta.aptible.com:form-flow-staging/demo.git ${GITHUB_SHA}:main
      - name: Announce on Slack when deploy fails
        if: failure()
        uses: ravsamhq/notify-slack-action@v2
        with:
          status: ${{ job.status }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      - name: Set aptible environment variables
        run: |
          wget -O aptible-package https://omnibus-aptible-toolbelt.s3.amazonaws.com/aptible/omnibus-aptible-toolbelt/master/206/pkg/aptible-toolbelt_0.16.5%2B20200508143656~ubuntu.16.04-1_amd64.deb
          sudo dpkg -i aptible-package

